# Generated by Django 6.1.1 on 2026-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('golden', 'Golden Era'), ('80s', '80s'), ('90s', '90s'), ('2000s', '2000s'), ('bangla', 'Bangla Classics'), ('hindi', 'Old Hindi'), ('english', 'Old English'), ('other', 'Other')], default='other', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('audio_file', models.FileField(upload_to='music/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
